#!/bin/bash
#
# Place this file in the folder containing the exported Bioclipse folder and
# run it to get the packaged versions
#
RELEASE=bioclipse.2.4.0.RC3
chmod -R 777 win32.win32.x86_64 win32.win32.x86
find . -name bioclipse.ini | xargs perl -i -pe 's/\r?\n// if /=\r?$/'
cd linux.gtk.x86
tar czvf ../$RELEASE.linux.gtk.x86.tar.gz *
cd ../linux.gtk.x86_64
tar czvf ../$RELEASE.linux.gtk.x86_64.tar.gz *
cd ../win32.win32.x86
zip -r ../$RELEASE.win32.win32.x86.zip *
cd ../win32.win32.x86_64
zip -r ../$RELEASE.win32.win32.x86_64.zip *
cd ..
cp -R macosx.cocoa.x86_64 $RELEASE.macosx.cocoa.x86_64
hdiutil create -srcfolder $RELEASE.macosx.cocoa.x86_64 $RELEASE.macosx.cocoa.x86_64.dmg
