#!/bin/bash
#
# Place this file in the folder containing the exported Bioclipse folder and
# run it to get the packaged versions
#
RELEASE=Bioclipse.2.4.0.RC1
chmod -R 777 win32.win32.x86_64 win32.win32.x86
find . -name bioclipse.ini | xargs perl -i -pe 's/\r?\n// if /=\r?$/'
tar czvf $RELEASE.linux.gtk.x86.tar.gz linux.gtk.x86
tar czvf $RELEASE.linux.gtk.x86_64 linux.gtk.x86_64
mv macosx.cocoa.x86_64 $RELEASE.macosx.cocoa.x86_64
hdiutil create -srcfolder $RELEASE.macosx.cocoa.x86_64 $RELEASE.macosx.cocoa.x86_64.dmg
zip -r $RELEASE.win32.win32.x86.zip linux.gtk.x86
zip -r $RELEASE.win32.win32.x86_64.zip win32.win32.x86_64
